name: Docker Latest

on:
  push:
    branches:
      - main

jobs:
  push_fpm:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    name: Tag Latest (PHP-FPM, ${{ matrix.base-tag }})

    strategy:
      fail-fast: false
      matrix:
        base-tag:
          - 8.3-fpm-alpine

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Quay
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_REPOSITORY_USERNAME }}
          password: ${{ secrets.DOCKER_REPOSITORY_TOKEN }}

      - name: Build and push
        id: docker
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          tags: quay.io/renokico/laravel-base:latest-${{ matrix.base-tag }}
          file: Dockerfile.fpm
          build-args: |
            BASE_TAG=${{ matrix.base-tag }}
